### ISSUE TITLE
Current Version Does not compile properly

### ISSUE THREAD

**Issue by bobstrecansky** [jguyomard/docker-yellowlabtools#1]
Thought i'd mention that running with current has an issue of using const in strict mode as defined [here](http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode)

v1.10 seems to work fine FYI.

Relevant output:
`[13:45:20] ~ git master ? docker run --rm -p 8383:8383 jguyomard/yellowlabtools                                                                                                                                                     1 ↵
Unable to find image 'jguyomard/yellowlabtools:latest' locally
latest: Pulling from jguyomard/yellowlabtools

fdd5d7827f33: Pull complete
a3ed95caeb02: Pull complete
0f35d0fe50cc: Pull complete
627b6479c8f7: Pull complete
67c44324f4e3: Pull complete
b52090f6ca00: Pull complete
8979b8896d07: Pull complete
f5fe9907caa5: Pull complete
6d733ce03317: Pull complete
f67cd301866b: Pull complete
Digest: sha256:2e5b0df60cc0b253cb03313ea94b879b4f3657f41108d9ddf03513c37d58146d
Status: Downloaded newer image for jguyomard/yellowlabtools:latest
/usr/src/ylt/node_modules/imagemin/index.js:2
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/src/ylt/lib/tools/redownload/imageOptimizer.js:3:27)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)`

**Comment by jguyomard** [comment]
Oh. Thank you for this issue!
I can't have a look right now, but i'll fix this in ~10 days.

**Comment by jguyomard** [comment]
OK, this issue is fixed, v1.11 works fine:

```
docker run --rm -p 8383:8383 jguyomard/yellowlabtools:1.11
```
