### ISSUE TITLE
Add branch for v1.13

### ISSUE THREAD

**Issue by Potherca** [jguyomard/docker-yellowlabtools#3]
YellowLabTools has release [version 1.13.](https://github.com/gmetais/YellowLabTools/releases/tag/v1.13.0)

It would be nice if it was added to this repository.

**Comment by Potherca** [comment]
👋 This is the obligatory ping. Any chance this issue can get some love? ❤️

**Comment by gmetais** [comment]
Hi there, maybe you can try this one: https://github.com/LumberjackOtters/docker-yellow-lab-tools

**Comment by Potherca** [comment]
@gmetais Thanks for the suggestion! I ended up creating (and updating) a `Dockerfile` myself. 

I'll make it public soonish through https://pipeline-components.dev/ that way it'll be available for Docker, GitLab, and GitHub all at once.
